### ISSUE TITLE
TODO-Pkmn Data Extension

### ISSUE THREAD

**Issue by TaZhiJingJie** [TaZhiJingJie/SW_sources#1]
- [ ] Repoint massive table
- [ ] Complete pkmn data set
- [ ] Delete old table data
