### ISSUE TITLE
TODO - Move and Ability Expansion

### ISSUE THREAD

**Issue by TaZhiJingJie** [TaZhiJingJie/SW_sources#5]
- [ ] Jambo51 moveset hHack
- [ ] Repoint Move Name table
- [ ] Repoint Move description table
- [ ] Repoint Move data sheet
- [ ] Repoint Ability Name table
- [ ] Repoint Ability description table
